services:
  postgres:
    image: postgres:15
    container_name: flight_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: silverlineage
      POSTGRES_PASSWORD: Fusion199!
      POSTGRES_DB: flight_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    container_name: flight_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
